# This is a basic workflow to help you get started with Actions

name: run spigot build

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '11'
      - name: download spigot
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: run spigot
        run: java -jar BuildTools.jar | grep -vE "[^/ ]*/[^/ ]*\s*KB\s*$" | grep -v "^\s*$"
      - name: find target
        shell: bash
        run: |
          cp $(find . -name "*.jar" -type f -exec stat --format '%Y :%y %n' "{}" \; | sort -nr | cut -d " " -f 5 | head -n 1) target.jar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: SpigotServer.jar
          path: target.jar
          
      
